name: musicpod
description: Ubuntu music, radio and podcast player.
version: 1.4.5

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  animated_emoji: ^3.1.0
  audio_metadata_reader: ^0.0.6
  audio_service: ^0.18.12
  audio_service_mpris:
    git:
      url: https://github.com/Feichtmeier/audio-service-mpris
      ref: ad6f743b73e320670449026fa1852d9978438bb9
  basic_utils: ^5.7.0
  blur: ^3.1.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  desktop_notifications: ^0.6.3
  dio: ^5.4.3
  file: ^7.0.0
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.2+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_tabler_icons: ^1.27.0
  github: ^9.24.0
  gtk: ^2.1.0
  handy_window: ^0.4.0
  http: ^1.2.1
  intl: ^0.18.0
  m3u_parser_nullsafe: ^1.0.3
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video/
      ref: 13f6b3f0ef9ccf8a711e396bc49cb05af9b3e497
  mime: ^1.0.5
  mime_type: ^1.0.0
  mockito: ^5.4.4
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path: ^1.9.0
  path_provider: ^2.1.2
  phoenix_theme:
    git:
      url: https://github.com/Feichtmeier/phoenix_theme
      ref: 4486490240ba42cc668079064ad41f3ae8869d01
  pls: ^1.1.0
  podcast_search: ^0.6.9
  radio_browser_api: ^2.0.0+1
  reorderableitemsview: ^2.0.1
  safe_change_notifier: ^0.3.2
  scroll_to_index: ^3.0.1
  shimmer: ^3.0.0
  smtc_windows: ^0.1.2
  super_drag_and_drop: ^0.8.15
  system_theme: ^2.3.1
  url_launcher: ^6.2.5
  watch_it: ^1.4.1
  window_manager: ^0.3.8
  xdg_directories: ^1.0.4
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart
      ref: 7b485d56d17576ff07964683c91d48eef1dc1297
  yaru_window: ^0.2.1
  yaru_window_linux: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/images/media-optical.png

dependency_overrides:
  intl: 0.19.0
  media_kit_native_event_loop:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_native_event_loop/
      ref: 13f6b3f0ef9ccf8a711e396bc49cb05af9b3e497
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video/
      ref: 13f6b3f0ef9ccf8a711e396bc49cb05af9b3e497
  uuid: ^4.1.0
