name: musicpod
description: Ubuntu music, radio and podcast player.
version: 1.3.5

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  animated_emoji: ^3.0.0
  audio_metadata_reader: ^0.0.4
  audio_service: ^0.18.12
  basic_utils: ^5.6.1
  blur: ^3.1.0
  cached_network_image: ^3.3.0
  collection: ^1.17.0
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  desktop_notifications: ^0.6.3
  dio: ^5.4.0
  file: ^7.0.0
  file_selector: ^1.0.0
  file_selector_linux: ^0.9.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15
  flutter_tabler_icons: ^1.7.0
  github: ^9.22.0
  gtk: ^2.1.0
  handy_window: ^0.4.0
  http: ^1.2.0
  intl: ^0.18.0
  m3u_parser_nullsafe: ^1.0.3
  media_kit: ^1.1.10
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  mime: ^1.0.4
  mime_type: ^1.0.0
  mockito: ^5.4.4
  mpris_service:
    git:
      url: https://github.com/alexmercerind/mpris_service
      ref: 3a4a721
  package_info_plus: ^6.0.0
  palette_generator: ^0.3.3+3
  path: ^1.9.0
  path_provider: ^2.1.2
  pls: ^1.1.0
  podcast_search: ^0.6.9
  radio_browser_api: ^2.0.0+1
  reorderableitemsview: ^2.0.1
  safe_change_notifier: ^0.3.2
  scroll_to_index: ^3.0.1
  shimmer: ^3.0.0
  smtc_windows: ^0.1.2
  super_drag_and_drop: ^0.7.0
  system_theme: ^2.3.1
  url_launcher: ^6.2.5
  watch_it: ^1.4.1
  window_manager: ^0.3.8
  xdg_directories: ^1.0.4
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart
      ref: 7b485d56d17576ff07964683c91d48eef1dc1297
  yaru_window: ^0.2.1
  yaru_window_linux: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - snap/gui/musicpod.png
    - assets/images/media-optical.png

dependency_overrides:
  intl: 0.19.0