app_id: 6B599538-42B1-4826-A479-AF079F21A65D
publisher: org.feichtmeier
publisher_url: https://github.com/ubuntu-flutter-community/musicpod
display_name: MusicPod
create_desktop_icon: true
install_dir_name: musicpod
locales:
  - da
  - de
  - en
  - es
  - fr
  - it
  - nl
  - pt_BR
  - ru
  - sk
  - zh
  - pt
