# TODO: fix AppImage release, see https://github.com/ubuntu-flutter-community/musicpod/issues/379
# Apart from snap which is released via ci/cd pipeline to edge and then manually promoted from edge to stable
# AppImage, Windows and MacOs releases should be created via this manual release action which is triggered when a tag is added to git
name: Release

on:
  push:
    branches:
      - release

env:
  FLUTTER_VERSION: '3.19.x'

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmpv-dev
      - run: flutter --disable-analytics
      - run: flutter pub get
      - run: flutter build linux --release
      - uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./AppImageBuilder.yml"
        env:
          UPDATE_INFO: gh-releases-zsync|ubuntu-flutter-community|musicpod|latest|*x86_64.AppImage.zsync
