name: Publish Snap

on:
  push:
    branches:
      - snap

env:
  FLUTTER_VERSION: '3.24.x'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version in pubspec.yaml
        id: check
        run: |
          echo "Head branch: ${GITHUB_HEAD_REF}"
          echo "Base branch: ${GITHUB_BASE_REF}"
          changed=$(git diff --unified=0 --merge-base ${GITHUB_BASE_REF} -- 'pubspec.yaml' | grep -n '^@@' | cut -d':' -f1)
          echo $changed >> $GITHUB_OUTPUT
          echo "lines changed: $changed"
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmpv-dev
      - run: flutter pub get
      - uses: snapcore/action-build@v1
        if: steps.check.outputs.changed == '5'
        id: build
      - uses: snapcore/action-publish@v1
        if: steps.build.outcome == 'success'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
