name: publish

on:
# JUST TO TEST IN THIS PR,
# TODO: CHANGE BACK TO
# push:
#   branches:
#     - main
  pull_request:
    branches: [main]


env:
  FLUTTER_VERSION: '3.13.x'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libmpv-dev
      - run: flutter pub get
      - run: flutter build linux -v
        id: build
      - uses: snapcore/action-build@v1
        if: steps.build.outcome == 'success'
        id: build_snap
      - uses: snapcore/action-publish@v1
        if: steps.build_snap.outcome == 'success'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build_snap.outputs.snap }}
          release: edge
